name: Build and push redis package
on:
  push:
    branches:
      - main

jobs:
  build-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:     

      - uses: actions/checkout@v3

      - name: install spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}

      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: install tinygo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: "v0.32.0"
      
      - name: build spinapp
        run: spin build
      
      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push package
        run: |
          RELEASE_VERSION=$(yq '.application.version' spin.toml) && \
          spin registry push ghcr.io/${{ github.repository }}:$RELEASE_VERSION && \
          spin registry push ghcr.io/${{ github.repository }}:latest